development:
bucket: dogood-dev
access_key_id: ENV['AWS_KEY']
secret_access_key: ENV['AWS_SECRET']
test:
bucket: dogood-test
access_key_id: ENV['AWS_KEY']
secret_access_key: ENV['AWS_SECRET']
production:
bucket: dogood-prod
access_key_id: ENV['AWS_KEY']
secret_access_key: ENV['AWS_SECRET']